---
# task file for setup
    - name: Download .rpm package
      get_url:
        dest: /tmp/epel-release-latest-7.noarch.rpm
        url: '{{ epel_url }}'
        force: no
    
    - name: Uninstall epel package if already installed
      package: 
        name: epel-release.noarch
        state: absent    

    - name: Install Downloaded .rpm package
      package:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: present
       
    - name: Update all
      package:
        name: '*'
        state: latest
    
    - name: Install necessary packages
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - '{{ system_packages }}'
     
    - name: Execute yum clean 
      command: yum clean all  

    - name: Uninstall pgdg package if already install
      package: 
        name: pgdg-centos95.noarch
        state: absent

    - name: Install pgdg package
      package:
        name: '{{ pgdg_url }}'
        state: present 

    - name: Uninstall older db packages
      package: 
        name: "{{item}}"
        state: absent
      with_items:
        - '{{ db_packages }}' 

    - name: Install postgresql package's
      package: 
        name: "{{item}}"
        state: latest
      with_items:
        - '{{ db_packages }}' 

    - name: Creating soft link
      file:
        src: /usr/pgsql-9.5/bin/pg_config
        dest: /usr/bin/pg_config
        state: link
