---
- name: roles
  hosts: All 
  become: true
  vars:
    db_name: "{{ DATABASE_NAME|default('transtats') }}"
    db_user: "{{ DATABASE_USER|default('postgres') }}"
    db_pass: "{{ DATABASE_PASSWD|default('postgres') }}"
    db_host: "{{ DATABASE_HOST|default('localhost') }}"
  tasks:
  - import_role:
      name: setup
    when: ansible_distribution == "Fedora"

  - import_role:
      name: rhel-setup
    when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL" 

  - import_role:
      name: db
    when: ansible_distribution == "Fedora"

  - import_role:
      name: rhel-db
    when: ansible_distribution == "CentOS" or ansible_distribution == "RHEL"  
      
  - import_role:
      name: env

  - import_role:
      name: deploy