---
- name: roles
  hosts: all 
  become: true
  gather_facts: true
  vars_files:
    - "env_vars/env.yml"
    - "vars/common-vars.yml"
    - "vars/{{ ansible_distribution }}-vars.yml"
  roles:
    - setup
    - db
    - env
    - deploy
