---
# task file for env setup
     - name: Install virtualenv
       command: 'pip3 install virtualenv'

     - name: create user transtats
       user:
         name: transtats
         shell: /bin/bash
         comment: "transtats"
         uid: 1040
         group: nginx
         
     - name: switch user to transtats
       command: '/bin/su - transtats'

     - name: Get url
       shell: curl -s https://api.github.com/repos/transtats/transtats/releases/latest | grep tarball_url | head -n 1 | cut -d '"' -f 4
       register: url

     - set_fact: 
         transtats_url: "{{ url.stdout }}"
         cacheable: true  

     - name: Download transtats tarfile 
       get_url:
         dest: /home/transtats/transtats.tar.gz
         url: "{{ transtats_url }}"
         force: yes   

     - name: Extract transtats.tar.gz into /home/transtats/
       unarchive:
         src: /home/transtats/transtats.tar.gz
         dest: /home/transtats/  
         remote_src: yes

     - name: Move code to /home/transtats/transtats-code
       shell: 'rm -rf /home/transtats/transtats && mv /home/transtats/transtats-transtats* /home/transtats/transtats'       

     - copy:
         src: /home/transtats/transtats/transtats/settings/keys.json.example
         dest: /home/transtats/transtats/transtats/settings/keys.json
         remote_src: yes   

     - command: 'cd /home/transtats/transtats'

     - name: Create virtual env
       command: 'virtualenv --system-site-packages --python=python3 projectenv'
     - name: activate virtual env
       shell: 'source projectenv/bin/activate'    

     - name: install requirements
       pip: 
         requirements: /home/transtats/transtats/requirements/base.txt
         virtualenv: /home/transtats/transtats/projectenv
         virtualenv_command: virtualenv

     - name: Run make migrate
       shell: 'cd /home/transtats/transtats && source projectenv/bin/activate && make migrate'  



     
     

   
