---
# task file for setup
    - name: Download .rpm package
      get_url:
        dest: /tmp/epel-release-latest-7.noarch.rpm
        url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        force: no
    
    - name: Uninstall epel package if already installed
      yum: 
        name: epel-release.noarch
        state: absent    

    - name: Install Downloaded .rpm package
      yum:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: present
      ignore_errors: yes
 
    - name: Update all
      yum:
        name: '*'
        state: latest
    
    - name: Install necessary packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - gcc
        - python34-devel
        - python34-pip
        - git
        - nginx
      ignore_errors: yes

    - name: Uninstall pgdg package if already install
      yum: 
        name: pgdg-centos95.noarch
        state: absent

    - name: Install pgdg package
      yum:
        name: http://yum.postgresql.org/9.5/redhat/rhel-7-x86_64/pgdg-centos95-9.5-2.noarch.rpm
        state: present 

    - name: Install postgresql package's
      yum: 
        name: "{{item}}"
        state: latest
      with_items:
        - postgresql95
        - postgresql95-server
        - postgresql95-libs
        - postgresql95-contrib
        - postgresql95-devel

    - name: Creating soft link
      file:
        src: /usr/pgsql-9.5/bin/pg_config
        dest: /usr/bin/pg_config
        state: link
