---
#task file for db setup
    - name: Delete data directory if exists
      command: rm -rf /var/lib/pgsql/9.5/data/

    - name: Init db
      command: '/usr/pgsql-9.5/bin/postgresql95-setup initdb'
      ignore_errors: yes
 
    - name: Start postgresql-9.5 service 
      service: 
        name: postgresql-9.5
        enabled: yes
        state: started

    - command: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"

    - command: sudo -u postgres psql -c "CREATE DATABASE transtats"
   
