---
# task file db 
    - name: Init db
      command: 'su - postgres -c "PGDATA=/var/lib/pgsql/data initdb -S"'
      ignore_errors: yes      

    - name: Change permission of /var/lib/pgsql/data
      file:
        path: /var/lib/pgsql/data
        owner: 26
        group: 26
        mode: 0700   

    # - copy:
    #     src:  /workspace/transtats/deploy/docker/conf/pg_hba.conf
    #     dest: /var/lib/pgsql/data/pg_hba.conf

    - name: Start postgresql service 
      service: 
        name: postgresql
        enabled: yes
        state: started 

    - name: Alter db user passwd
      command: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"

    - name: Create database 
      postgresql_db:
        name: transtats
        encoding: UTF-8
        lc_collate: en_US.UTF-8
        lc_ctype: en_US.UTF-8
        template: template0
        login_host: localhost
        port: 5432
        login_user: postgres
        login_password: postgres